export const BACKEND_API_END_POINT = "http://localhost:8080";
// export const BACKEND_API_END_POINT = "https://group-5-5mpu.onrender.com";
export const STUDENT_API_END_POINT=`${BACKEND_API_END_POINT}/elevateu/v1/student`;
export const COUNSELLOR_API_END_POINT=`${BACKEND_API_END_POINT}/elevateu/v1/counsellor`;
export const OTP_API_END_POINT=`${BACKEND_API_END_POINT}/elevateu/v1/otp`;
export const AI_API_END_POINT=`${BACKEND_API_END_POINT}/elevateu/v1/aipage`;
export const FIND_USER_API_END_POINT=`${BACKEND_API_END_POINT}/elevateu/v1/user`;
export const CHAT_API_END_POINT=`${BACKEND_API_END_POINT}/elevateu/v1/chat`;
export const ADMIN_API_END_POINT=`${BACKEND_API_END_POINT}/elevateu/admin`;